
main: 
	java -jar ../bin/closure-cli.jar build templates stylesheets javascript html --compile

development:
	java -jar ../bin/closure-cli.jar build templates stylesheets javascript html

interactive:
	java -jar ../bin/closure-cli.jar
